FROM reg.vip.blibee.com/opsk8s/java_server_8u221_prod_eks:latest
RUN mv /home/w/www/default.wormpex.com_prod/ DEPLOY_PATH && touch /RSYNC_FILE_MD5 \
    && mv /home/w/tools_prod /home/w/tools 
COPY * RSYNC_DST/ 
